#include "tloc_smart_ptr.h"
#include "tloc_smart_ptr.inl.h"

using namespace tloc;

TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char8);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(uchar8);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(ushort);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s8);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s16);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s64);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f64);

TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char8*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(uchar8*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(ushort*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s8*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s16*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s64*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f64*);