#include "tloc_smart_ptr.h"
#include "tloc_smart_ptr.inl.h"
#include "tloc_smart_ptr.opt.inl.h"

using namespace tloc;

TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char8);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(uchar8);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(short);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(ushort);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s8);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s64);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f64);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u32);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u64);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(tl_long);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(tl_ulong);

TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char8*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(uchar8*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(char32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(short*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(ushort*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s8*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s64*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(f64*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u32*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u64*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(tl_long*);
TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(tl_ulong*);

// NOTE: s16, u8, u16 all conflict with other explicit instantiations on iOS
// This is due to the types not having unique base types
// i.e. uchart8 and u8 have a base type of unsigned char
#if !defined (TLOC_OS_IPHONE)
  TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s16);
  TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u8);
  TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u16);

  TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(s16*);
  TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u8*);
  TLOC_EXPLICITLY_INSTANTIATE_ALL_SMART_PTRS(u16*);
#endif