#include "tlocTuple.h"
#include "tlocTuple.inl.h"

namespace tloc { namespace core { namespace data_structs {

  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(f32, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(f64, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(s32, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(s64, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(u32, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(u64, 2);

  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(f32, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(f64, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(s32, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(s64, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(u32, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(u64, 3);

  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(f32, 4);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(f64, 4);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(s32, 4);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(s64, 4);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(u32, 4);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(u64, 4);

  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(tl_size, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(tl_size, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(tl_size, 4);

  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(bool, 2);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(bool, 3);
  TLOC_EXPLICITLY_INSTANTIATE_TUPLE(bool, 4);

};};};