#include "tlocVariadic.h"
#include "tlocVariadic.inl.h"

namespace tloc { namespace core { namespace data_structs {

#include "tlocVariadicTypedefMacros.h"
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(char8);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(char32);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(s32);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(s64);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(u32);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(u64);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(f32);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(f64);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(f128);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(tl_ulong);
  TLOC_EXPLICITLY_INSTANTIATE_VARIADIC_TYPES(tl_size);

};};};
