#include "tlocVector.h"
#define TLOC_VECTOR_ALLOW_EASY_OPERATIONS
#include "tlocVector.opt.inl.h"

#include <tlocMath/tlocMath.inl.h>

namespace tloc { namespace math { namespace types {

#include "tlocVectorExplicitMacros.h"
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR_ALL_ACCURACIES(f32,  1);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f64,  1);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f128, 1);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR_ALL_ACCURACIES(f32,  2);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f64,  2);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f128, 2);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR_ALL_ACCURACIES(f32,  3);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f64,  3);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f128, 3);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR_ALL_ACCURACIES(f32,  4);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f64,  4);
  TLOC_EXPLICITLY_INSTANTIATE_VECTOR(f128, 4);

};};};