#include <tlocCore/containers/tlocArray.h>
#include <tlocCore/containers/tlocArray.inl.h>

using namespace tloc;

TLOC_EXPLICITLY_INSTANTIATE_ARRAY(s8);
TLOC_EXPLICITLY_INSTANTIATE_ARRAY(s32);
TLOC_EXPLICITLY_INSTANTIATE_ARRAY(s64);

TLOC_EXPLICITLY_INSTANTIATE_ARRAY(u8);
TLOC_EXPLICITLY_INSTANTIATE_ARRAY(u32);
TLOC_EXPLICITLY_INSTANTIATE_ARRAY(u64);

TLOC_EXPLICITLY_INSTANTIATE_ARRAY(f32);
TLOC_EXPLICITLY_INSTANTIATE_ARRAY(f64);

TLOC_EXPLICITLY_INSTANTIATE_ARRAY(tl_ulong);
