#include "tlocList.h"
#include "tlocList.inl.h"

using namespace tloc;

TLOC_EXPLICITLY_INSTANTIATE_LIST(s8);
TLOC_EXPLICITLY_INSTANTIATE_LIST(s32);
TLOC_EXPLICITLY_INSTANTIATE_LIST(s64);

TLOC_EXPLICITLY_INSTANTIATE_LIST(u8);
TLOC_EXPLICITLY_INSTANTIATE_LIST(u32);
TLOC_EXPLICITLY_INSTANTIATE_LIST(u64);

TLOC_EXPLICITLY_INSTANTIATE_LIST(f32);
TLOC_EXPLICITLY_INSTANTIATE_LIST(f64);

TLOC_EXPLICITLY_INSTANTIATE_LIST(tl_int);
TLOC_EXPLICITLY_INSTANTIATE_LIST(tl_ulong);
TLOC_EXPLICITLY_INSTANTIATE_LIST(tl_size);
TLOC_EXPLICITLY_INSTANTIATE_LIST(tl_uintptr);
TLOC_EXPLICITLY_INSTANTIATE_LIST(tl_ptrdiff);