#include "tlocStrongType.h"
#include "tlocStrongType.inl"

#include "tlocStrongTypeExplicitMacros.h"
  TLOC_INSTANTIATE_STRONG_TYPE(s8);
  TLOC_INSTANTIATE_STRONG_TYPE(u8);

  TLOC_INSTANTIATE_STRONG_TYPE(s32);
  TLOC_INSTANTIATE_STRONG_TYPE(s64);

  TLOC_INSTANTIATE_STRONG_TYPE(u32);
  TLOC_INSTANTIATE_STRONG_TYPE(u64);

  TLOC_INSTANTIATE_STRONG_TYPE(f32);
  TLOC_INSTANTIATE_STRONG_TYPE(f64);
  TLOC_INSTANTIATE_STRONG_TYPE(f128);