#ifndef TLOC_VERSION_H
#define TLOC_VERSION_H

// << IF YOU HAVE A CONFLICT, READ THIS >> 
// Auto-generated file for automatic versioning. Do not edit this file 
// directly unless you are editing a CONFLICT, in which case simply 
// increment the time and your current build number to resolve the 
// conflict.
// e.g. local-file version = x_x_5_12345 where 12345 = time and 
// incoming-file version = x_x_8_12350 where 12350 = time then... 
// take the build number (5) and increment it and increment the time (12345)
// so the local-file will then have: x_x_6_12346
// (please see end-of-file for rationalle behind this)

#ifndef TLOC_VERSION_0_1_10758_1397741919
#  error "You are building against an incorrect/older version of the library. The correct version is the macro above."
#endif

#endif

// Rationale behind incrementing the build number and time is that 
// it will reduce the chances of a version number conflicting with 
// another previous version (or a version we do not know about yet 
// as our repository may not be up-to-date)